### ISSUE TITLE
remove bottle :unneeded

### ISSUE THREAD

**Issue by es183923** [railwayapp/homebrew-railway#2]
IT seems that GoReleaser automatically added back `bottle :unneeded`. Update [GoReleaser](https://github.com/goreleaser/goreleaser) to [v0.183.0](https://github.com/goreleaser/goreleaser/releases/tag/v0.183.0) to fix this.

**Comment by JakeCooper** [comment]
Thanks! We run latest so I'll actually just fire another build/tag/etc and that should resolve it :D
